import streamlit as st
import pandas as pd
from database.connection import SessionLocal
from services.analytics import get_route_analytics, get_route_rankings
from services.recommendations import generate_recommendations, get_recommendations
from services.export import export_to_csv

st.set_page_config(page_title="AI Recommendations", page_icon="💡", layout="wide")
st.title("💡 AI Recommendations Engine")
st.warning("⚠️ **ADVISORY DISCLAIMER:** Recommendations are auto-generated by the Rule Engine from historical data. They do not account for fuel prices, competitor actions, or regulatory changes. **Human review required before taking operational action.**")

db = SessionLocal()

col1, col2 = st.columns([3, 1])
with col1:
    st.markdown("The AI scans the entire network to identify inefficiencies, capacity constraints, and growth opportunities.")
with col2:
    if st.button("🔄 Run AI Network Scan", type="primary"):
        with st.spinner("Analyzing network..."):
            try:
                _df = get_route_analytics(db)
                _rank = get_route_rankings(_df)
                success, msg = generate_recommendations(db, _rank)
                if success:
                    st.success(msg)
                    st.cache_data.clear()
                else:
                    st.error(msg)
            except Exception as e:
                st.error(f"Scan failed: {e}")

# Sidebar filters (FR-404)
st.sidebar.header("Filter & Sort")
recs_data = get_recommendations(db)

if not recs_data:
    st.info("No recommendations yet. Click **Run AI Network Scan** to generate them.")
    db.close()
    st.stop()

all_types = sorted(set(r.Recommendation.recommendation_type.value for r in recs_data))
all_conf  = sorted(set(r.Recommendation.confidence_level for r in recs_data))
sel_type  = st.sidebar.multiselect("Action Type", all_types, default=all_types)
sel_conf  = st.sidebar.multiselect("Confidence", all_conf, default=all_conf)
sort_by   = st.sidebar.radio("Sort by", ["Confidence (High→Low)", "Route ID", "Type"])

# Filter
filtered = [
    r for r in recs_data
    if r.Recommendation.recommendation_type.value in sel_type
    and r.Recommendation.confidence_level in sel_conf
]

conf_order = {"High": 0, "Medium": 1, "Low": 2}
if sort_by == "Confidence (High→Low)":
    filtered = sorted(filtered, key=lambda r: conf_order.get(r.Recommendation.confidence_level, 9))
elif sort_by == "Route ID":
    filtered = sorted(filtered, key=lambda r: r.Route.route_id)
elif sort_by == "Type":
    filtered = sorted(filtered, key=lambda r: r.Recommendation.recommendation_type.value)

st.markdown(f"**Showing {len(filtered)} recommendation(s)**")

color_map = {
    "Upgrade Aircraft": "green",
    "Increase Frequency": "blue",
    "Reduce Capacity": "orange",
    "Review Profitability": "red",
    "Expand Route": "violet",
    "Monitor": "grey",
}

for r in filtered:
    rec   = r.Recommendation
    route = r.Route
    val   = rec.recommendation_type.value
    color = color_map.get(val, "grey")
    with st.expander(f":{color}[{val}] — {route.route_id} ({route.origin_city} ➔ {route.destination_city})  |  Confidence: {rec.confidence_level}"):
        st.markdown(f"**AI Rationale:** {rec.rationale}")
        st.caption(f"Generated on {rec.generated_at.strftime('%Y-%m-%d %H:%M')} UTC")

# CSV export (FR-505 / FR-404)
st.markdown("---")
if filtered:
    export_rows = [{
        'Route': r.Route.route_id,
        'Origin': r.Route.origin_city,
        'Destination': r.Route.destination_city,
        'Action': r.Recommendation.recommendation_type.value,
        'Confidence': r.Recommendation.confidence_level,
        'Rationale': r.Recommendation.rationale,
        'Generated': r.Recommendation.generated_at.strftime('%Y-%m-%d'),
    } for r in filtered]
    export_df = pd.DataFrame(export_rows)
    st.download_button("📥 Export Recommendations CSV", export_to_csv(export_df), "recommendations.csv", "text/csv")

db.close()
